CREATE DEFINER=`root`@`localhost` PROCEDURE `igecom`.`P_GAIA_PLACE_ORDER`(
IN P_QUOTE_ID INT
)
BEGIN
DECLARE V_ORDERID INT;

BEGIN

DECLARE V_TXR_NO_REC_FOUND INTEGER DEFAULT 0;
DECLARE V_PARAM1 VARCHAR(256);
DECLARE V_PARAM2 VARCHAR(256);
DECLARE V_PARAM3 VARCHAR(256);
DECLARE V_PARAM4 VARCHAR(256);
DECLARE V_PARAM5 VARCHAR(256);
DECLARE V_PARAM6 VARCHAR(256);
DECLARE V_PARAM7 VARCHAR(256);
DECLARE V_PARAM8 VARCHAR(256);
DECLARE V_PARAM9 VARCHAR(256);
DECLARE V_PARAM10 VARCHAR(256);
DECLARE V_PARAM11 VARCHAR(256);
DECLARE V_PARAM12 VARCHAR(256);

DECLARE SALES_QUOTE_CURSOR CURSOR FOR
SELECT 
`customer_id`,
`is_active`,
`website_id`,
`currency`,

`total_items`,
`total_items_qty`,
`grand_total`,
`shipping_amount`,
`tax_amount`,

`coupon_code`,
`cod_charges`,
`payment_method` 

FROM `sales_quote` WHERE `id` = P_QUOTE_ID AND `is_active` = 1;
DECLARE CONTINUE HANDLER 
FOR NOT FOUND SET V_TXR_NO_REC_FOUND = 1;
        
OPEN SALES_QUOTE_CURSOR;
SALES_QUOTE :
LOOP
FETCH SALES_QUOTE_CURSOR INTO 
V_PARAM1,
V_PARAM2,
V_PARAM3,
V_PARAM4,
V_PARAM5,

V_PARAM6,
V_PARAM7,
V_PARAM8,
V_PARAM9,
V_PARAM10,

V_PARAM11,
V_PARAM12;

IF V_TXR_NO_REC_FOUND = 1 THEN 
LEAVE SALES_QUOTE;
END IF; 

SELECT COALESCE((MAX(`id`)+1),1) INTO V_ORDERID FROM `sales_order`;
   INSERT INTO `sales_order`
(
`id`,
`customer_id`,
`display_id`,
`website_id`,
`currency`,

`total_items`,
`total_items_qty`,
`grand_total`,
`shipping_amount`,
`tax_amount`,

`coupon_code`,
`cod_charges`,
`payment_method`,
`created_at`,`updated_at`
)
VALUES
(
V_ORDERID,
V_PARAM1,
'OD001260541',
V_PARAM3,
V_PARAM4,
V_PARAM5,

V_PARAM6,
V_PARAM7,
V_PARAM8,
V_PARAM9,
V_PARAM10,

V_PARAM11,
V_PARAM12,
NOW(),NOW()
);   
   
END LOOP SALES_QUOTE ;
CLOSE SALES_QUOTE_CURSOR ;

END;




BEGIN

DECLARE V_TXR_NO_REC_FOUND INTEGER DEFAULT 0;
DECLARE V_PARAM1 VARCHAR(256);
DECLARE V_PARAM2 VARCHAR(256);
DECLARE V_PARAM3 VARCHAR(256);
DECLARE V_PARAM4 VARCHAR(256);
DECLARE V_PARAM5 VARCHAR(256);
DECLARE V_PARAM6 VARCHAR(256);
DECLARE V_PARAM7 VARCHAR(256);
DECLARE V_PARAM8 VARCHAR(256);
DECLARE V_PARAM9 VARCHAR(256);
DECLARE V_PARAM10 VARCHAR(256);
DECLARE V_PARAM11 VARCHAR(256);
DECLARE V_PARAM12 VARCHAR(256);

DECLARE SALES_QUOTE_ADDR_CURSOR CURSOR FOR
SELECT 
`firstname`,`lastname`,`street`,`country`,`region`,`area`,`postcode`

FROM `sales_quote_address` WHERE `quote_id` = P_QUOTE_ID;
DECLARE CONTINUE HANDLER 
FOR NOT FOUND SET V_TXR_NO_REC_FOUND = 1;
        
OPEN SALES_QUOTE_ADDR_CURSOR;
SALES_QUOTE_ADDR:
LOOP
FETCH SALES_QUOTE_ADDR_CURSOR INTO 
 
V_PARAM2,
V_PARAM3,
V_PARAM4,
V_PARAM5,

V_PARAM6,
V_PARAM7,
V_PARAM8;

IF V_TXR_NO_REC_FOUND = 1 THEN 
LEAVE SALES_QUOTE_ADDR;
END IF; 

   INSERT INTO `sales_order_address`
(
`order_id`,`firstname`,`lastname`,`street`,`country`,`region`,`area`,`postcode`,`created_at`,`updated_at`

)
VALUES
(
V_ORDERID,
V_PARAM2,
V_PARAM3,
V_PARAM4,
V_PARAM5,

V_PARAM6,
V_PARAM7,
V_PARAM8,
NOW(),NOW()
);   
   
END LOOP SALES_QUOTE_ADDR ;
CLOSE SALES_QUOTE_ADDR_CURSOR ;

END;


BEGIN

DECLARE V_TXR_NO_REC_FOUND INTEGER DEFAULT 0;
DECLARE V_PARAM1 VARCHAR(256);
DECLARE V_PARAM2 VARCHAR(256);
DECLARE V_PARAM3 VARCHAR(256);
DECLARE V_PARAM4 VARCHAR(256);
DECLARE V_PARAM5 VARCHAR(256);
DECLARE V_PARAM6 VARCHAR(256);
DECLARE V_PARAM7 VARCHAR(256);
DECLARE V_PARAM8 VARCHAR(256);
DECLARE V_PARAM9 VARCHAR(256);
DECLARE V_PARAM10 VARCHAR(256);
DECLARE V_PARAM11 VARCHAR(256);
DECLARE V_PARAM12 VARCHAR(256);

DECLARE SALES_QUOTE_ITEM_CURSOR CURSOR FOR
SELECT 
`product_id`,`product_name`,`price`,`cost`,`sku`,`product_type`

FROM `sales_quote_items` WHERE `quote_id` = P_QUOTE_ID;
DECLARE CONTINUE HANDLER 
FOR NOT FOUND SET V_TXR_NO_REC_FOUND = 1;
        
OPEN SALES_QUOTE_ITEM_CURSOR;
SALES_QUOTE_ITEM:
LOOP
FETCH SALES_QUOTE_ITEM_CURSOR INTO 
V_PARAM1,
V_PARAM2,
V_PARAM3,
V_PARAM4,
V_PARAM5,

V_PARAM6;

IF V_TXR_NO_REC_FOUND = 1 THEN 
LEAVE SALES_QUOTE_ITEM;
END IF; 

   INSERT INTO `sales_order_items`
(
`order_id`,`product_id`,`product_name`,`price`,`cost`,`sku`,`product_type`,`created_at`,`updated_at`

)
VALUES
(
V_ORDERID,
V_PARAM1,
V_PARAM2,
V_PARAM3,
V_PARAM4,
V_PARAM5,

V_PARAM6,
NOW(),NOW()
);   
   
END LOOP SALES_QUOTE_ITEM;
CLOSE SALES_QUOTE_ITEM_CURSOR;

END;


BEGIN

DECLARE V_TXR_NO_REC_FOUND INTEGER DEFAULT 0;
DECLARE V_PARAM1 VARCHAR(256);
DECLARE V_PARAM2 VARCHAR(256);
DECLARE V_PARAM3 VARCHAR(256);
DECLARE V_PARAM4 VARCHAR(256);
DECLARE V_PARAM5 VARCHAR(256);
DECLARE V_PARAM6 VARCHAR(256);
DECLARE V_PARAM7 VARCHAR(256);
DECLARE V_PARAM8 VARCHAR(256);
DECLARE V_PARAM9 VARCHAR(256);
DECLARE V_PARAM10 VARCHAR(256);
DECLARE V_PARAM11 VARCHAR(256);
DECLARE V_PARAM12 VARCHAR(256);

DECLARE SALES_QUOTE_PAYMENT_CURSOR CURSOR FOR
SELECT 
`method`,`cc_type`,`cc_last4`,`cc_owner`,`cc_exp_month`,`cc_exp_year`,`additional_data`

FROM `sales_quote_payment` WHERE `quote_id` = P_QUOTE_ID;
DECLARE CONTINUE HANDLER 
FOR NOT FOUND SET V_TXR_NO_REC_FOUND = 1;
        
OPEN SALES_QUOTE_PAYMENT_CURSOR;
SALES_QUOTE_PAYMENT:
LOOP
FETCH SALES_QUOTE_PAYMENT_CURSOR INTO 
V_PARAM1,
V_PARAM2,
V_PARAM3,
V_PARAM4,
V_PARAM5,

V_PARAM6,
V_PARAM7;

IF V_TXR_NO_REC_FOUND = 1 THEN 
LEAVE SALES_QUOTE_PAYMENT;
END IF; 

   INSERT INTO `sales_order_payment`
(
`order_id`,`method`,`cc_type`,`cc_last4`,`cc_owner`,`cc_exp_month`,`cc_exp_year`,`additional_data`,`created_at`,`updated_at`
)
VALUES
(
V_ORDERID,
V_PARAM1,
V_PARAM2,
V_PARAM3,
V_PARAM4,
V_PARAM5,

V_PARAM6,
V_PARAM7,
NOW(),NOW()
);   
   
END LOOP SALES_QUOTE_PAYMENT;
CLOSE SALES_QUOTE_PAYMENT_CURSOR;

END;

DELETE FROM `sales_quote` WHERE `id` = P_QUOTE_ID;
DELETE FROM `sales_quote_address` WHERE `quote_id` = P_QUOTE_ID;
DELETE FROM `sales_quote_items` WHERE `quote_id` = P_QUOTE_ID;
DELETE FROM `sales_quote_payment` WHERE `quote_id` = P_QUOTE_ID;


    END