
logging:
    level:
        ROOT: INFO
        com.lectrefy: INFO

spring: 
    mvc:
        view:
            prefix: /jsp/
            suffix: .jsp
    application:
        name: gaia-ecom-service
    profiles:
        active: dev
        include:
    jackson:
        date-format: "yyyy-MM-dd HH:mm:ss"
        serialization:
            write_dates_as_timestamps: false
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://167.99.153.79:3306/igecom?useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: Achu2106
        hikari:
            auto-commit: false
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        show-sql: true
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.connection.provider_disables_autocommit: true
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            
    mail:
        host: smtp.gmail.com
        port: 587
        username: info@ignovatesolutions.com
        password: Achu2106
        properties:
            mail.smtp.auth: true
            mail.smtp.starttls.enable: true
            mail.smtp.starttls.required: true
            mail.smtp.connectiontimeout: 5000
            mail.smtp.timeout: 5000
            mail.smtp.writetimeout: 5000

server:
    port: 8081
    servlet:
        context-path: /${spring.application.name}

sms:
    url: http://global.myvaluefirst.com/smpp/sendsms
    sender:
        id: SMSALERT
        username: demohttpt
        password: httpdemoT
    register:
        template: Sign Up Success
    reset:
        template: Changed Password
    otp:
        template: Sign Up
email:
    otp:
        text: your otp is
    register:
        subject: Account created
        text: your account created in lectrefy
    update:
        subject: Account updated
        text: your account updated in lectrefy

authman:
    url : http://localhost:8082/gaia-ecom-authman/api/authman/v1.0/validate
    disable: /**